Foysal
shafiqrbs/tbd-frontend pull request #57
Opened 2024-12-02 11:52 UTC by foysal-mahmud-hasan

2024-12-02 14:54 UTC, Rashedul-Raju-3m requested changes
check this

2024-12-02 14:54 UTC, Rashedul-Raju-3m commented on src/components/modules/core/vendor/VendorForm.jsx
> +            customer_id : isNotEmpty()
### why not empty ? it's not required field.

2024-12-02 14:54 UTC, Rashedul-Raju-3m commented on src/components/modules/core/vendor/VendorForm.jsx
> -                                                    tooltip={
why remove this ? if customer select & already exists , how to show the instant error message?

2024-12-02 15:06 UTC, Rashedul-Raju-3m commented on src/components/modules/core/vendor/VendorForm.jsx
> -                                                    tooltip={
may be you not up to date, because i fixed this issue today.

2024-12-03 05:09 UTC, foysal-mahmud-hasan commented on src/components/modules/core/vendor/VendorForm.jsx
> -                                                    tooltip={
Bhai I rolled back changes in vendor form. kindly check .

2024-12-08 08:39 UTC, merged